# Generated by Django 5.0.2 on 2024-11-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0002_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('teamlead_development', 'TeamLead_Development'), ('content_moderators', 'Content Moderators'), ('teamlead_content_moderators', 'TeamLead_Content Moderators'), ('sales_team', 'Sales Team'), ('teamlead_sales_team', 'TeamLead_Sales Team'), ('customer_support', 'Customer Support Team'), ('teamlead_customer_support', 'TeamLead_Customer Support Team')], max_length=30, null=True),
        ),
    ]
