# Generated by Django 5.0.2 on 2024-11-08 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0006_attendance_break_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leave_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
