# Generated by Django 5.0.2 on 2024-11-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0014_alter_employee_aadhar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overall_experience',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
