# Generated by Django 5.0.2 on 2024-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0015_employee_overall_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='overall_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
