# Generated by Django 5.0.2 on 2024-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0016_alter_employee_overall_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='previous_Total_work_experience',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Enter in this format(2 years 3 months)'),
        ),
    ]
