# Generated by Django 5.0.2 on 2024-11-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0017_alter_employee_previous_total_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='previous_Total_work_experience',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Prvious Experience (Enter in this format(2 years 3 months))'),
        ),
    ]
