# Generated by Django 5.0.2 on 2024-11-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0019_alter_employee_previous_total_work_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='overall_experience',
        ),
    ]
